config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  resources :games do 
    resources :reviews
    resources :userreviews
  end
  resources :editors
  resources :consoles

  get 'about' =>'welcome#about'

end

app/views/shared/_reviewform.html.erb
<%= form_for ([@game, @review]) do |f| %>
  <h3>Add a review</h3>
  <div class="question-group">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>
  <div class="question-group">
    <label for="review[editor_id]">Editor</label>
    <select name="review[editor_id]" id="review[editor_id]">
      <% Editor.all.each do |editor| %>
        <option value="<%= editor.id %>"><%= editor.name %></option>
      <% end %>
    </select>
  </div>
  <div class="question-group">
    <%= f.label :score %>
    <%= f.text_field :score %>
  </div>
  <%= f.submit "save", class: "btn btn-primary" %>
<% end %>

app/views/shared/_reviews.html.erb
<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Reviews</h3>
    </div>
    <div class="panel-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope='col'>Title</th>
            <th scope='col'>Editor</th>
            <th scope='col'>Score</th>
          </tr>
        </thead>  
        <tbody>
          <% reviews.each do |review| %>
            <% if review.id %>
              <tr>
                <td>
                  <%= link_to review.game.title, game_path(review.game) %>
                </td> 
                <td>
                  <%= link_to review.editor.name, editor_path(review.editor) %>
                </td>
                <td><strong><%= review.score %></score></td>
                <td>
                  <%= link_to 'read', review.link %>
                </td>
                <td>
                  <%= link_to 'delete', game_review_path(review.game, review),
                            method: :delete,
                            data: { confirm: 'Are you sure?' } %>
                </td>
            <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/shared/_userreviewform.html.erb
<%= form_for ([@game, @game.userreviews.build]) do |f| %>
  <h3>Your Score</h3>
  <div class="question-group">
    <label for="userreview[score]">Score</label>
    <select name="userreview[score]" id="userreview[score]">
      <% 1.upto(100) do |score| %>
        <option value="<%= score %>" <%= score == @user_score ? 'selected' : '' %> >
          <%= score %>
        </option>
      <% end %>
    </select>
  </div>
  <input type='hidden' name='userreview[user_id]' value="<%= current_user.id %>">
  <%= f.submit "save", class: "btn btn-primary" %>
<% end %>