config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  resources :games do 
    resources :reviews
    resources :userreviews
  end
  resources :editors
  resources :consoles

  get 'about' =>'welcome#about'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @games = params[:q] ? Game.search_for(params[:q]) : Game.last(10).reverse
    @editors = params[:q] ? Editor.search_for(params[:q]) : Editor.last(10).reverse
  end
  
  def about
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<div class="container">
  <div class="col-md-8">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>About</h3>
      </div>
      <div class="panel-body">
        <p>
        Critic is a new way to look at reviews. We are flooded every day with reviews and it can cause
        normal purchasing decisions to be crippiling. 
        </p>
        <p>Parsing out which reviews are legitimate can be very time consuming. Critic seeks to solve 
        this by finding the people that matter to you.</p>
        <p>By matching your tastes, the system learns what you likes, and finds you the most compatible users. It brings these users and professionals to your attention so you can follow interact and find out about new media that may interest you.</p>
        <p>Using this system we can provide a better aggregate score based on your likes and dislikes.</p>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to Criteek</h1>
  </div>
</div>
<div class="container">
  <p>
    <% if can? :create, Game %>
      <%= link_to "Add a Game", new_game_path %>
    <% end %>
    <% if can? :create, Editor %>
      <%= link_to "Add an Editor", new_editor_path %>
    <% end %>
  </p>
  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Games</h3>
        </div>
        <div class="panel-body">
          <table class="table table-striped">
            <tr>
              <th scope='col'>Title</th>
              <th scope='col'>Average</th>
              <% if can? :update, Game %>
                <th></th>
              <% end %>
              <% if can? :destroy, Game %>
                <th></th>
              <% end %>
            </tr>
            <%= render @games %>
          </table>
          <div><%= link_to 'all games ->', games_path %></div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Editors</h3>
        </div>
        <div class="panel-body">
          <table class="table table-striped">
            <%= render @editors %>
          </table>
          <div><%= link_to 'all editors -> ', editors_path %></div>
        </div>
      </div>
    </div>
  </div>
</div>