config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  resources :games do 
    resources :reviews
    resources :userreviews
  end
  resources :editors
  resources :consoles

  get 'about' =>'welcome#about'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  has_many :users, through: :userreviews
  has_many :userreviews
  has_and_belongs_to_many :consoles
  has_attached_file :boxart, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :boxart, :content_type => /\Aimage\/.*\Z/
  validates :title, presence: true
  validates :description, presence: true



  def meta_score user_id=nil
    if self.reviews.any?
      if user_id
        weighted_meta_score user_id
      else
        normal_meta_score
      end
    else
      "N/A"
    end
  end

  def normal_meta_score
    reviews = self.reviews
    total = 0
    reviews.each do |review|
      unless review.id.nil?
        total = review.score + total
      end
    end
    total / reviews.count
  end

  def weighted_meta_score user_id
    if self.reviews.any?
      reviews = self.reviews
      total = 0
      reviews_count = 0
      weighted_reviews = []

      ############################################
      #Figure out the weight of each add to toatal
      ############################################
      reviews.each do |review|
        unless review.id.nil?
          metaweight = Metaweight.where("user_id = :user_id AND editor_id = :editor_id", 
                                    {user_id: user_id, editor_id: review.editor.id})
          if metaweight.any?
            weighted_reviews << {review: review, weight: metaweight.last.weight}
          else
            weighted_reviews << {review: review, weight: 100000.0}
          end
        end
      end
      weighted_reviews = weighted_reviews.sort_by {|h| h[:weight]}
      weighted_reviews.reverse!

      mult = 2
      weighted_reviews.each_with_index do |weighted_review, index|
        unless weighted_review.nil?
          if weighted_review[:weight] > 10000.0
            total = weighted_review[:review].score + total
            reviews_count = reviews_count + 1
          else
            total = (weighted_review[:review].score * mult) + total
            reviews_count = reviews_count + mult
            mult = mult + 1
          end
        end
      end
      if reviews_count == 0
        'N/A'
      else
        total / reviews_count
      end
      ############################################
      #/end
      ############################################
    else
      "N/A"
    end
  end


  def self.search query
    where('title LIKE :query OR description LIKE :query', query: "%#{query}%")
  end
end

app/controllers/games_controller.rb
require 'pry'
class GamesController < ApplicationController
  def index
    @games = Game.all
  end
  
  def show
    @game = Game.find params[:id]
    @review = @game.reviews.build
    if can? :create, Userreview
      if @game.userreviews.any?
        @user_score = @game.userreviews.where(user_id: current_user.id) #.last.score
        if @user_score.any?
          @user_score = @user_score.last.score
        end
      else
        @user_score = 1
      end
    end
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new game_params
    save_console_associations(@game)

    if @game.save
      redirect_to @game
    else
      render :new
    end
  end

  def edit
    @game = Game.find params[:id]
  end

  def update
    @game = Game.find params[:id]
    @game.consoles.delete_all
    save_console_associations(@game)
    if @game.update(game_params)
      redirect_to @game
    else
      render :edit
    end
  end

  def destroy 
    @game = Game.find params[:id]
    @game.destroy
    redirect_to :root
  end

  private
  def game_params
    params.require(:game).permit(:title, :description, :releasedate, :boxart, :console_id => [])
  end

  def console_params
    params.require(:console).permit(:console_id => [])
  end

  def save_console_associations game 
    console_ids = console_params[:console_id]
    console_ids.reject! {|c| c.empty? }
    if console_ids.any?
      game.consoles << Console.find(console_ids)
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_game.html.erb
<tr>
  <td><%= link_to game.title, game_path(game) %></td>
  <td><strong><%= number_with_precision(game.meta_score(current_user), precision: 1) %>%</strong></td>
  
  <% if can? :update, game %>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
  <% end %>

  <% if can? :destroy, game %>
    <td><%= link_to 'Delete', game_path(game),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</tr>

app/views/games/_gameform.html.erb
<%= form_for @game do |f| %>
    <div class='form-group'>    
      <%= f.label :title, class: 'control-label' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class='form-group'>
      <%= f.label :description, class: 'control-label' %>
      <%= f.text_area :description,  class: 'form-control' %>
    </div>

    <div class='form-group'>
      <%= f.label :releasedate, class: 'control-label'%>
      <%= f.date_select :releasedate,  class: 'form-control' %>
    </div>

    <div class='form-group'>
      <%= f.label :boxart, 'Box Art (jpg, png)', class: 'control-label' %>
      <%= f.file_field :boxart,  class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= collection_check_boxes(:console, :console_id, Console.all, :id, :abbr, {:item_wrapper_class => 'checkbox'}) %>
    </div>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/games/edit.html.erb
<div class = 'errors'>
    <% if @game.errors.any? %>
      <ul>
        <% @game.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
</div>
<div class="container">
  <div class="col-md-6">
    <div class="panel panel-info">
      <div class='panel-heading'>
        <h2>Edit <%= @game.title %></h2>
      </div>
      <div class="panel-body">
        <%= render 'gameform'%>
      </div>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<div class="container">
  <h2 class="sub-header">Games</h2>
  <div class="table-responsive">
    <table class="table table-striped datatable">
      <thead>
        <tr>
          <th>Name</th>
          <th>Consoles</th>
          <th>Release Dates</th>
          <th>Reviews</th>
          <th>Review Avg</th>
        </tr>
      </thead>
      <tbody>
        <% @games.each do |g| %>
          <tr>
            <td><%= link_to g.title, game_path(g) %></td>
            <td>
              <% g.consoles.each do |c| %>
                <%= link_to c.abbr, console_path(c) %>
              <% end %>
            </td>
            <td><%= g.releasedate %></td>
            <td><%= g.reviews.count %></td>
            <td><%= number_with_precision(g.meta_score(current_user), precision: 1)%>%</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <script>
    $(document).ready( function () { 
      $('.datatable').DataTable();
    });
  </script>
</div>

app/views/games/new.html.erb
<div class = 'errors'>
    <% if @game.errors.any? %>
      <ul>
        <% @game.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
</div>
<div class="container">
  <div class="col-md-6">
    <div class="panel panel-info">
      <div class='panel-heading'>
        <h2>Add a game</h2>
      </div>
      <div class="panel-body">
        <%= render 'gameform'%>
      </div>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="container">
  <h1><%= @game.title %></h1>
  <div>
    <% if can? :update, @game %>
    <%= link_to 'Edit', edit_game_path(@game) %>, 
    <% end %>
    <% if can? :destroy, @game %>
      <%= link_to 'Delete', game_path(@game),
                          method: :delete,
                          data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>                        
  <p>
    <strong>Description: </strong>
    <%= @game.description %>
  </p>
  <p>
    <strong>Consoles: </strong>
    <% @game.consoles.each do |c| %>
      <%= link_to c.abbr, console_path(c) %>
    <% end %>
  </p>

  <div class='boxart'><%= image_tag @game.boxart.url(:thumb), class: 'img-thumbnail' %></div>
  <div> 
    <strong>Average Score: </strong>
      <%= number_with_precision(@game.meta_score(current_user), precision: 1) %>%
  </div>
  <% if can? :create, Userreview %>
    <div class='review-form'>
      <%= render 'shared/userreviewform' %>
    </div>
  <% end %>
  <% if can? :create, Review %>
    <div class='review-form'>
      <%= render 'shared/reviewform' %>
    </div>
  <% end %>
  <div class="row">
    <%= render partial: 'shared/reviews', object: @game.reviews %>
  </div>
</div.