config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  resources :games do 
    resources :reviews
    resources :userreviews
  end
  resources :editors
  resources :consoles

  get 'about' =>'welcome#about'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Critic', '/', html_options = {class: 'navbar-brand'} %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class='<%= cp(root_path) %>'><%= link_to 'Home', '/'%></li>
        <li class='<%= cp(games_path) %>'><%= link_to 'Games', games_path %></li>
        <li class='<%= cp(editors_path) %>'><%= link_to 'Editors', editors_path %></li>


        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <!-- <li><a href="#">Link</a></li> -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Consoles <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/consoles/1">Xbox One</a></li>
            <li><a href="/consoles/2">Xbox 360</a></li>
            <li><a href="/consoles/3">Xbox</a></li>
            <li class="divider"></li>
            <li><a href="/consoles/4">Playstation 4</a></li>
            <li><a href="/consoles/5">Playstation 3</a></li>
            <li><a href="/consoles/6">Playstation 2</a></li>
            <li><a href="/consoles/7">Playstation</a></li>
            <li class="divider"></li>
            <li><a href="/consoles/8">Wii U</a></li>
            <li><a href="/consoles/9">Wii</a></li>
            <li><a href="/consoles/10">Gamecube</a></li>
            <li><a href="/consoles/11">N64</a></li>
          </ul>
        </li>
        <li class='<%= cp(about_path) %>'><%= link_to 'About', about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
      <!--<form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->
      <!-- <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CriticApp</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

  <!-- DataTables CSS -->
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.css">


  <!--<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>-->
  <script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.10.2.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div><%= notice %></div>
  <div><%= alert %></div>
  <%= render 'layouts/header' %>
  <%= yield %>
</body>
</html>